[package]
name = "nd-godot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.2.1", features = ["api-4-3"] }
nd-engine = { workspace = true }
serde_json = { workspace = true }
