[package]
name = "nd-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
assets_manager = { version = "0.12.4", features = ["hot-reloading"] }
clap = "4.5.23"
glium = "0.36.0"
log = "0.4.22"
nd-core = { path = "../nd-core" }
serde_json = "1.0.134"
